# Generated by Django 4.2.16 on 2024-12-06 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('destination', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tour_type', models.CharField(choices=[('beach', 'Пляжний'), ('excursion', 'Екскурсійний'), ('ski', 'Гірськолижний'), ('adventure', 'Пригодницький'), ('cruise', 'Круїзний'), ('wellness', 'Оздоровчий'), ('safari', 'Сафарі'), ('culinary', 'Кулінарний'), ('cultural', 'Культурний'), ('ecotourism', 'Екотуризм')], max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/')),
            ],
        ),
    ]
